/**
 * AddALevelWords.gs — a one-off import. Run it once, then delete this file.
 *
 * Adds the A Level Chemistry and Maths vocabulary from the Obsidian vault as
 * words in two folders, "A Level Chem" and "A Level Math". Each entry carries
 * the Japanese sense first and the English definition under it, and two
 * example sentences in the note — the kind of sentence the term appears in on
 * an Edexcel paper.
 *
 * How to run it
 *   1. Paste this file into the same Apps Script project as Code.gs — it uses
 *      the helpers there, so Code.gs must already be the current version.
 *   2. Pick addALevelWords in the function list and press Run.
 *   3. Read the log for the counts.
 *
 * Safe to run twice: a word already in the same folder is skipped rather than
 * added again, and nothing that is already in the sheet is modified. Every
 * row is written in one go, so the whole import is a single write.
 */

var CHEM_FOLDER = 'A Level Chem';
var MATH_FOLDER = 'A Level Math';

/** [word, part of speech, definition (Japanese then English), two examples] */
var CHEM_WORDS = [
  ['Anion', 'Noun',
   '陰イオン。電子を受け取って負の電荷をもつイオン。非金属がつくる。\nA negatively charged ion, formed when an atom gains electrons. Non-metals form anions.',
   'Chlorine gains one electron to form a chloride anion.\nThe anion is attracted towards the positive electrode.'],
  ['Cation', 'Noun',
   '陽イオン。電子を失って正の電荷をもつイオン。金属がつくる。\nA positively charged ion, formed when an atom loses electrons. Metals form cations.',
   'Sodium loses one electron to form a cation with a 1+ charge.\nMetallic bonding is the attraction between cations and delocalised electrons.'],
  ['Atomic Orbital', 'Noun',
   '原子軌道。原子核のまわりで、スピンが逆向きの電子を最大2個まで収容できる空間の領域。\nA region of space around the nucleus that can hold up to two electrons of opposite spin.',
   'Each atomic orbital holds a maximum of two electrons.\nThe 2p sub-shell is made up of three atomic orbitals of equal energy.'],
  ['Atomic Radius', 'Noun',
   '原子半径。原子の大きさの尺度。族を下がるほど大きく、周期を右に進むほど小さくなる。\nA measure of the size of an atom. It increases down a group and decreases across a period.',
   'Explain why the atomic radius decreases across Period 3.\nThe atomic radius increases down Group 2 because an extra shell is added.'],
  ['Electron', 'Noun',
   '電子。原子核の外にある負の電荷をもつ粒子。相対電荷は −1、質量は無視できるほど小さい。\nA negatively charged particle outside the nucleus, with relative charge −1 and a negligible relative mass.',
   'An atom has the same number of electrons as protons, so it is neutral overall.\nThe electron is removed from the outermost shell first.'],
  ['Electronegativity', 'Noun',
   '電気陰性度。共有結合中の共有電子対を自分の方へ引きつける原子の能力。\nThe ability of an atom to attract the shared electrons in a covalent bond towards itself.',
   'Fluorine has the highest electronegativity of any element.\nA difference in electronegativity between two atoms produces a polar bond.'],
  ['Electronic Configuration', 'Noun',
   '電子配置。原子の電子が殻・副殻・軌道にどう配置されているか。\nThe arrangement of an atom’s electrons across its shells, sub-shells and orbitals.',
   'Write down the electronic configuration of a calcium atom.\nThe electronic configuration of oxygen is 1s2 2s2 2p4.'],
  ['Group', 'Noun',
   '族。周期表の縦の列。同じ族の元素は最外殻電子の数が等しい。\nA vertical column of the periodic table. Elements in the same group have the same number of electrons in their valence shell.',
   'All the elements in Group 2 have two electrons in their outer shell.\nReactivity increases down the group.'],
  ['Period', 'Noun',
   '周期。周期表の横の行。同じ周期の元素は電子殻の数が等しい。\nA horizontal row of the periodic table. Elements in the same period have the same number of electron shells.',
   'Across Period 3 the atomic radius decreases.\nSodium and chlorine are in the same period.'],
  ['Hund’s Rule', 'Noun',
   'フントの規則。同じ副殻の軌道には、まず平行なスピンで1個ずつ電子が入り、その後で対をつくる。\nElectrons occupy the orbitals of a sub-shell singly, with parallel spins, before any pairing takes place.',
   'By Hund’s rule the three 2p electrons of nitrogen occupy separate orbitals.\nState Hund’s rule and use it to explain the configuration of oxygen.'],
  ['Pauli Exclusion Principle', 'Noun',
   'パウリの排他原理。1つの軌道に入る電子は最大2個で、スピンは互いに逆向きでなければならない。\nOne orbital holds at most two electrons, and they must have opposite spins.',
   'The Pauli exclusion principle limits each orbital to two electrons.\nExplain, using the Pauli exclusion principle, why the first shell holds only two electrons.'],
  ['Ionic Radius', 'Noun',
   'イオン半径。イオンの大きさ。金属イオンは元の原子より小さく、非金属イオンは大きい。\nThe size of an ion. Metal ions are smaller than their atoms; non-metal ions are larger.',
   'The ionic radius of sodium is smaller than its atomic radius.\nSuggest why the ionic radius of chloride is larger than that of the chlorine atom.'],
  ['Ionisation Energy', 'Noun',
   'イオン化エネルギー。気体状態の原子1モルから電子を1個ずつ取り去り、1価の陽イオン1モルにするのに必要なエネルギー。単位は kJ mol⁻¹。\nThe energy needed to remove one electron from each atom in one mole of gaseous atoms, forming one mole of gaseous 1+ ions.',
   'Define the term first ionisation energy.\nThe first ionisation energy decreases down Group 2.'],
  ['Successive Ionisation Energies', 'Noun',
   '逐次イオン化エネルギー。同じ原子から電子を次々に取り去るのに必要なエネルギーの列。大きな飛びは新しい内殻の始まりを示す。\nThe series of energies needed to remove electrons one after another from the same atom; a big jump marks the start of a new, closer quantum shell.',
   'The successive ionisation energies show a large jump between the second and third electron.\nUse the successive ionisation energies to deduce the group of the element.'],
  ['Isotope', 'Noun',
   '同位体。陽子の数が同じで中性子の数が異なる同一元素の原子。原子番号は同じ、質量数は異なる。\nAtoms of the same element with the same number of protons but a different number of neutrons.',
   'Chlorine has two common isotopes, 35Cl and 37Cl.\nExplain why isotopes of the same element have identical chemical properties.'],
  ['Neutron', 'Noun',
   '中性子。原子核内にある電荷をもたない粒子。相対電荷 0、相対質量 1。\nAn uncharged particle in the nucleus, with relative charge 0 and relative mass 1.',
   'The number of neutrons is the mass number minus the atomic number.\nNeutrons are not deflected in a magnetic field because they have no charge.'],
  ['Proton', 'Noun',
   '陽子。原子核内にある正の電荷をもつ粒子。相対電荷 +1、相対質量 1。\nA positively charged particle in the nucleus, with relative charge +1 and relative mass 1.',
   'The number of protons defines which element an atom is.\nAn atom with 11 protons is sodium.'],
  ['Nucleus', 'Noun',
   '原子核。陽子と中性子を含む原子の中心部で、密度が非常に高い。\nThe dense centre of the atom containing the protons and neutrons.',
   'Almost all the mass of an atom is concentrated in the nucleus.\nThe electrons are attracted to the positive nucleus.'],
  ['Nuclear Charge', 'Noun',
   '核電荷。陽子の数で決まる原子核全体の正電荷。大きいほど電子を強く引きつける。\nThe total positive charge of the nucleus, set by the number of protons. A larger nuclear charge pulls the electrons in more strongly.',
   'The nuclear charge increases across a period.\nExplain how nuclear charge affects the first ionisation energy.'],
  ['Shielding', 'Noun',
   '遮蔽。内側の満たされた電子殻が、外側の電子に核電荷が十分に届かないようにする働き。\nThe way full inner shells of electrons prevent the outer electrons from feeling the full nuclear charge.',
   'Shielding increases down the group, so the outer electron is easier to remove.\nExplain, in terms of shielding, why the first ionisation energy falls down Group 1.'],
  ['Spin-pair Repulsion', 'Noun',
   'スピン対反発。1つの軌道を共有する2個の電子の間に働く余分な反発。片方が取り去られやすくなる。\nThe extra repulsion felt by two electrons sharing one orbital, which makes the first of them easier to remove.',
   'Spin-pair repulsion explains the small drop between Group 5 and Group 6.\nThe paired electron is removed more easily because of spin-pair repulsion.'],
  ['Quantum Shell', 'Noun',
   '量子殻（電子殻）。電子が入る主エネルギー準位。内側から2個、8個…と埋まっていく。\nA principal energy level holding electrons; shells fill outwards, the first holding 2 electrons and the second 8.',
   'The third quantum shell can hold up to 18 electrons.\nElectrons in the same quantum shell are roughly the same distance from the nucleus.'],
  ['Sub-shell', 'Noun',
   '副殻。量子殻を s, p, d, f に細分したもの。同じエネルギーの原子軌道からなる。\nA subdivision of a quantum shell (s, p, d, f), made up of atomic orbitals of equal energy.',
   'The 3p sub-shell is filled after the 3s sub-shell.\nState the number of orbitals in a d sub-shell.'],
  ['Valence Shell', 'Noun',
   '最外殻（価電子殻）。電子が入っている一番外側の殻で、結合に関わる電子がある。\nThe outermost occupied electron shell of an atom — the electrons that take part in bonding.',
   'Group 2 elements have two electrons in their valence shell.\nThe valence shell electrons are the ones lost or shared in bonding.'],
  ['Relative Atomic Mass', 'Noun',
   '相対原子質量。炭素12原子の質量の1/12を基準とした、その元素の原子の平均質量。記号 Ar、単位なし。\nThe weighted mean mass of an atom of an element, compared with one twelfth the mass of a carbon-12 atom. Symbol Ar, no units.',
   'Calculate the relative atomic mass of chlorine from its isotopic abundances.\nThe relative atomic mass of magnesium is 24.3.'],
  ['Relative Molecular Mass', 'Noun',
   '相対分子質量。分子中のすべての原子の相対原子質量の和。記号 Mr、単位なし。\nThe sum of the relative atomic masses of all the atoms in a molecule. Symbol Mr, no units.',
   'The molecular ion peak gives the relative molecular mass of the compound.\nCalculate the relative molecular mass of ethanol.'],
  ['Unified Atomic Mass Unit', 'Noun',
   '統一原子質量単位。炭素12原子の質量の1/12（1 u = 1.66 × 10⁻²⁷ kg）。相対質量の基準。\nOne twelfth of the mass of one carbon-12 atom: 1 u = 1.66 × 10⁻²⁷ kg. It is the reference for all relative masses.',
   'Masses on a mass spectrum are given in unified atomic mass units.\nOne unified atomic mass unit is defined from carbon-12.'],
  ['Pauling Scale', 'Noun',
   'ポーリングの尺度。電気陰性度の大きさで元素を並べた数値尺度。約0.7（セシウム）から4.0（フッ素）まで。\nThe numerical scale that orders elements by electronegativity, running from about 0.7 to 4.0.',
   'On the Pauling scale, oxygen has an electronegativity of 3.5.\nName the scale that orders the electronegativity of elements.'],
  ['Covalent Bonding', 'Noun',
   '共有結合。2つの原子が電子対を共有してできる分子内の結合。\nA shared pair of electrons between two atoms. An intramolecular bond.',
   'Covalent bonding holds the two hydrogen atoms together in H2.\nExplain why covalent bonding is stronger than hydrogen bonding.'],
  ['Ionic Bonding', 'Noun',
   'イオン結合。金属から非金属へ電子が移動してできた、反対符号のイオン間の静電引力。\nThe electrostatic attraction between oppositely charged ions, formed by the transfer of electrons from a metal to a non-metal.',
   'Ionic bonding in sodium chloride gives a giant lattice.\nDescribe what happens to the electrons during ionic bonding.'],
  ['Metallic Bonding', 'Noun',
   '金属結合。金属陽イオンの格子と、自由に動く非局在電子の海との間の引力。\nThe attraction between a lattice of metal cations and a sea of delocalised electrons.',
   'Metallic bonding explains why metals conduct electricity.\nThe strength of the metallic bonding increases with the charge on the cation.'],
  ['Intermolecular Forces', 'Noun',
   '分子間力。分子と分子の間に働く力。ファンデルワールス力、双極子間相互作用、水素結合など。分子内の結合より弱い。\nForces between separate molecules: van der Waals forces, dipole–dipole interactions and hydrogen bonding. Weaker than intramolecular bonds.',
   'Boiling a liquid overcomes the intermolecular forces, not the covalent bonds.\nExplain why the intermolecular forces in water are unusually strong.'],
  ['Intramolecular Forces', 'Noun',
   '分子内力。分子の中で原子どうしを結びつけている力（共有・イオン・金属結合）。分子間力より強い。\nForces within a molecule, holding the atoms together: covalent, ionic and metallic bonding. They are stronger than intermolecular forces.',
   'Intramolecular forces are not broken when a substance boils.\nDistinguish between intermolecular and intramolecular forces.'],
  ['Hydrogen Bonding', 'Noun',
   '水素結合。N, O, F に結合した水素と、別の分子の N, O, F の孤立電子対との間に働く、最も強い分子間力。\nThe strongest intermolecular force: an attraction between hydrogen bonded to N, O or F and a lone pair on the N, O or F of another molecule.',
   'Hydrogen bonding gives water its unusually high boiling point.\nDraw a diagram to show hydrogen bonding between two ammonia molecules.'],
  ['London Dispersion Forces', 'Noun',
   'ロンドン分散力。電子雲に生じる瞬間的な双極子によって、無極性分子どうしに働く引力。\nAttractions between non-polar molecules caused by instantaneous, temporary dipoles in the electron cloud.',
   'London dispersion forces increase with the number of electrons in the molecule.\nOnly London dispersion forces act between the noble gas atoms.'],
  ['Van der Waals Forces', 'Noun',
   'ファンデルワールス力。弱い分子間引力の総称。電子の数が多い分子ほど強い。\nThe general name for weak intermolecular attractions. They are stronger when a molecule has more electrons.',
   'The boiling point rises down Group 7 because the van der Waals forces get stronger.\nExplain, in terms of van der Waals forces, why iodine is a solid at room temperature.'],
  ['Dipole-Dipole Interaction', 'Noun',
   '双極子間相互作用。極性分子がもつ永久的な部分電荷どうしの引力。\nThe attraction between the permanent partial charges of polar molecules.',
   'Dipole–dipole interactions act between HCl molecules.\nCompare the strength of dipole–dipole interactions with that of hydrogen bonds.'],
  ['Electrostatic Interaction', 'Noun',
   '静電相互作用。電荷どうしの引力または斥力。同符号は反発し、異符号は引き合う。\nAttraction or repulsion between charges. Like charges repel, opposite charges attract.',
   'Ionic bonding is an electrostatic interaction between ions.\nThe electrostatic interaction is stronger when the ions are smaller.'],
  ['Electron Cloud', 'Noun',
   '電子雲。原子や分子のまわりで電子がつくる負電荷の領域。ゆがんだり偏ったりする。\nThe region of negative charge formed by the electrons around an atom or molecule; it can be distorted or polarised.',
   'A larger electron cloud is more easily polarised.\nThe electron cloud is distorted by a neighbouring dipole.'],
  ['Partial Charge', 'Noun',
   '部分電荷。極性結合の両端の原子がもつわずかな正・負の電荷（δ+、δ−）。\nThe small positive or negative charge (δ+ and δ−) on the atoms at either end of a polar bond.',
   'Label the partial charges on the H–Cl bond.\nThe oxygen atom carries a partial negative charge.'],
  ['Polar Bond', 'Noun',
   '極性結合。電気陰性度の異なる原子間の共有結合で、共有電子が一方に偏り部分電荷が生じる。\nA covalent bond between atoms of different electronegativity, so the shared electrons sit closer to one atom.',
   'The O–H bond is a polar bond.\nExplain why a C–Cl bond is polar but a C–C bond is not.'],
  ['Boiling Point', 'Noun',
   '沸点。1気圧のもとで液体が気体になる温度。記号 Bp。\nThe temperature at which a liquid becomes a gas at 1 atmosphere of pressure.',
   'State and explain the trend in boiling point down Group 7.\nWater has a higher boiling point than expected because of hydrogen bonding.'],
  ['Melting Point', 'Noun',
   '融点。1気圧のもとで固体が液体になる温度。記号 Tm。\nThe temperature at which a solid changes to a liquid at 1 atmosphere of pressure.',
   'Ionic compounds have high melting points.\nSuggest why the melting point of magnesium is higher than that of sodium.'],
  ['Evaporation', 'Noun',
   '蒸発。沸点より低い温度でも、液体の表面から最もエネルギーの高い粒子が抜け出す現象。\nThe escape of the highest-energy particles from the surface of a liquid, at any temperature below the boiling point.',
   'Evaporation cools the liquid that is left behind.\nExplain the difference between evaporation and boiling.'],
  ['Condensation', 'Noun',
   '凝縮。冷却により気体が液体になる変化。粒子が運動エネルギーを失い、引力が強まって近づく。\nThe change from gas to liquid on cooling, as particles lose kinetic energy and are pulled closer together.',
   'Condensation occurs on the cold surface of the flask.\nDescribe, in terms of particles, what happens during condensation.'],
  ['Freezing', 'Noun',
   '凝固。冷却により液体が固体になる変化。粒子が滑り合うのをやめる。\nThe change from liquid to solid on cooling, as particles lose kinetic energy and stop sliding past each other.',
   'Freezing takes place at the same temperature as melting.\nExplain, in terms of particle motion, what happens on freezing.'],
  ['Dynamic Equilibrium', 'Noun',
   '動的平衡。正反対の2つの過程が同じ速さで進み、見かけ上変化がない状態。\nA state in which two opposite processes continue at equal rates, so nothing appears to change.',
   'In a closed jar, evaporation and condensation reach a dynamic equilibrium.\nExplain what is meant by dynamic equilibrium.'],
  ['Vapour Pressure', 'Noun',
   '蒸気圧。同じ物質の気相と液相の間に成り立つ平衡による圧力。すべての物質に常に存在する。\nThe pressure of the equilibrium established between the gas phase and the liquid phase of the same substance.',
   'Vapour pressure increases as the temperature rises.\nA liquid boils when its vapour pressure equals the external pressure.'],
  ['Enthalpy Change of Vaporisation', 'Noun',
   '蒸発エンタルピー変化。液体1モルを気体1モルに変えるのに必要なエネルギー。\nThe energy required to change one mole of a liquid into one mole of a gas.',
   'The enthalpy change of vaporisation of water is unusually large.\nCalculate the energy needed, using the enthalpy change of vaporisation.'],
  ['Kinetic Energy', 'Noun',
   '運動エネルギー。粒子の運動によるエネルギー。加熱で増え、冷却で減る。\nThe energy of motion of a particle. Particles gain it on heating and lose it on cooling.',
   'The particles with the most kinetic energy escape from the surface.\nHeating the gas increases the average kinetic energy of its particles.'],
  ['Kinetic Theory of Gases', 'Noun',
   '気体分子運動論。気体粒子は絶えず高速でランダムに運動し、粒子間の距離は粒子自体よりはるかに大きく、互いに力を及ぼさないとするモデル。\nThe model that gas particles are in constant, rapid, random motion, far apart, and exerting no forces on each other.',
   'State the assumptions of the kinetic theory of gases.\nThe kinetic theory of gases explains why a gas fills its container.'],
  ['Ideal Gas', 'Noun',
   '理想気体。粒子の体積が無視でき、衝突が弾性的で、分子間力が働かない気体。pV = nRT に厳密に従う。\nA gas with negligible particle volume, elastic collisions and no intermolecular forces; it obeys pV = nRT exactly.',
   'Assume the gas behaves as an ideal gas.\nState two conditions under which a real gas approaches ideal behaviour.'],
  ['Real Gas', 'Noun',
   '実在気体。粒子が体積をもち互いに引力を及ぼすため、特に高圧・低温で理想からずれる気体。\nAn actual gas, which deviates from ideal behaviour because its particles occupy volume and attract one another.',
   'A real gas deviates most from ideal behaviour at high pressure and low temperature.\nExplain why a real gas does not obey pV = nRT exactly.'],
  ['Elastic Collision', 'Noun',
   '弾性衝突。運動エネルギーが失われない衝突。理想気体ではすべての衝突がこれと仮定される。\nA collision in which no kinetic energy is lost. Assumed for all collisions in an ideal gas.',
   'Collisions between ideal gas particles are perfectly elastic.\nState what is meant by an elastic collision.'],
  ['Compressibility', 'Noun',
   '圧縮性。物質がどれだけ押し縮められるか。気体は圧縮でき、液体や固体はほとんどできない。\nHow much a substance can be squeezed. Gases are compressible; liquids and solids are not.',
   'Explain the difference in compressibility between a gas and a liquid.\nThe high compressibility of a gas is due to the space between its particles.'],
  ['Temperature', 'Noun',
   '温度。物質中の粒子の平均運動エネルギーの尺度。高いほど粒子は速く動く。\nA measure of the average kinetic energy of the particles in a substance.',
   'Convert the temperature to kelvin before using pV = nRT.\nAt a higher temperature the particles have more kinetic energy.'],
  ['States of Matter', 'Noun',
   '物質の三態。固体・液体・気体（およびプラズマ）。どの状態になるかは分子間の結合と系のエネルギーで決まる。\nSolid, liquid and gas. Which state a substance is in depends on its intermolecular bonding and the energy of the system.',
   'Describe the arrangement of particles in the three states of matter.\nThe states of matter differ in how freely the particles can move.'],
  ['Noble Gases', 'Noun',
   '希ガス。第18族の元素。単原子で無極性のため、弱いファンデルワールス力しか働かず、ほぼ理想気体としてふるまう。\nGroup 18 elements. They exist as single, non-polar atoms, so only weak van der Waals forces act between them.',
   'The noble gases behave almost ideally at room temperature.\nExplain why the boiling points of the noble gases increase down the group.'],
  ['Monatomic, Diatomic and Polyatomic', 'Expression',
   '単原子・二原子・多原子。1粒子を構成する原子の数による分類（He、O₂、P₄ など）。\nHow many atoms make up one particle of a substance: one, two, or many.',
   'Helium is monatomic, whereas oxygen is diatomic.\nState whether sulfur, S8, is monatomic, diatomic or polyatomic.'],
  ['Mole', 'Noun',
   'モル。物質量の単位で、6.022 × 10²³ 個の粒子を含む量。式中の比を表すときにも使う。\nA unit of amount of substance: the amount containing 6.022 × 10²³ particles.',
   'Calculate the number of moles of sodium chloride in 5.85 g.\nOne mole of any gas occupies 24 dm3 at r.t.p.'],
  ['Avogadro’s Number', 'Noun',
   'アボガドロ数。1モルに含まれる粒子の数、6.022 × 10²³。炭素12の12 g 中の原子数に由来する。\n6.022 × 10²³ — the number of particles in one mole.',
   'Multiply the number of moles by Avogadro’s number to find the number of atoms.\nState the value of Avogadro’s number.'],
  ['Molar Mass', 'Noun',
   'モル質量。物質1モルあたりの質量。記号 M、単位 g mol⁻¹。\nThe mass per mole of a substance. Symbol M, units g mol⁻¹.',
   'The molar mass of carbon dioxide is 44.0 g mol⁻¹.\nDivide the mass by the molar mass to find the number of moles.'],
  ['Molar Volume', 'Noun',
   'モル体積。気体1モルが占める体積。室温・大気圧では約24 dm³。気体の種類によらずほぼ同じ。\nThe volume occupied by 1 mol of any gas — normally 24 dm3 at r.t.p.',
   'Use the molar volume to find the volume of 0.25 mol of oxygen.\nThe molar volume is nearly the same for all gases.'],
  ['Molar Ratio', 'Noun',
   'モル比。反応する物質の整数比。化学反応式からそのまま読み取る。\nThe whole-number ratio in which substances react, read straight off the balanced equation.',
   'The molar ratio of hydrogen to oxygen in water is 2 : 1.\nUse the molar ratio to calculate the mass of product formed.'],
  ['Stoichiometry', 'Noun',
   '化学量論。反応物と生成物の量的関係（モル比）を扱う分野。\nThe study of the quantitative relationships — the mole ratios — between reactants and products.',
   'Use the stoichiometry of the equation to find the limiting reactant.\nThe stoichiometry shows that two moles of hydrogen react with one mole of oxygen.'],
  ['Empirical Formula', 'Noun',
   '実験式（組成式）。化合物中の各元素の原子数の最も簡単な整数比。\nThe smallest whole-number ratio of atoms of each element in a compound.',
   'Calculate the empirical formula of the oxide from the masses given.\nThe empirical formula of glucose is CH2O.'],
  ['Molecular Formula', 'Noun',
   '分子式。分子中の各元素の実際の原子数。実験式の整数倍になる。\nThe actual number of atoms of each element in a molecule — a whole-number multiple of the empirical formula.',
   'Deduce the molecular formula from the empirical formula and the relative molecular mass.\nThe molecular formula of ethanoic acid is C2H4O2.'],
  ['Percentage Composition by Mass', 'Expression',
   '質量パーセント組成。化合物の全質量に各元素が占める割合を百分率で表したもの。実験式計算の出発点。\nThe proportion of the total mass of a compound contributed by each element, given as a percentage.',
   'Calculate the percentage composition by mass of nitrogen in ammonium nitrate.\nThe percentage composition by mass is the usual starting point for an empirical formula.'],
  ['Actual Yield', 'Noun',
   '実収量。実験で実際に得られた生成物の質量。損失や副反応のため理論収量より必ず少ない。\nThe mass of product actually obtained from an experiment — always less than the theoretical yield.',
   'The actual yield was 3.2 g.\nSuggest two reasons why the actual yield is lower than the theoretical yield.'],
  ['Theoretical Yield', 'Noun',
   '理論収量。反応が完全に進み損失がないと仮定したときに、化学反応式から予測される生成物の質量。\nThe mass of product that the balanced equation predicts, assuming the reaction goes to completion with no losses.',
   'Calculate the theoretical yield of copper sulfate.\nThe theoretical yield assumes that no product is lost.'],
  ['Percentage Yield', 'Noun',
   '収率。実収量を理論収量で割り100を掛けた値。\nThe actual yield divided by the theoretical yield, × 100%.',
   'Calculate the percentage yield of the reaction.\nA low percentage yield may be due to an incomplete reaction.'],
  ['Atom Economy', 'Noun',
   '原子効率。反応物の質量のうち目的生成物になる割合。反応の無駄の少なさを示す。\nThe proportion of the mass of the reactants that ends up in the desired product.',
   'Calculate the atom economy for this reaction.\nAddition reactions have a high atom economy.'],
  ['Hydrated Compound', 'Noun',
   '水和物。結晶中に結晶水を含む化合物。例：硫酸銅(II)五水和物 CuSO₄·5H₂O。\nA compound whose crystals contain water of crystallisation, e.g. CuSO4·5H2O.',
   'Heat the hydrated compound until its mass is constant.\nThe hydrated compound is blue, and the anhydrous form is white.'],
  ['Anhydrous Compound', 'Noun',
   '無水物。結晶水を含まない化合物。水和物を加熱してつくる。\nA compound that contains no water of crystallisation, made by heating the hydrate.',
   'The anhydrous compound turns blue when water is added.\nWeigh the anhydrous compound after cooling in a desiccator.'],
  ['Water of Crystallisation', 'Expression',
   '結晶水。結晶構造に一定の比で取り込まれた水分子。化学式では中黒のあとに示す。\nWater molecules taken up into a crystal structure in a fixed ratio, shown after a centre dot in the formula.',
   'Calculate the number of moles of water of crystallisation in the sample.\nThe water of crystallisation is driven off on heating.'],
  ['Mass Spectrometer', 'Noun',
   '質量分析計。試料を気化・イオン化し、加速して磁場で曲げ、質量電荷比ごとに検出する装置。\nThe instrument that vaporises a sample, ionises it, accelerates and deflects the ions in a magnetic field, and detects them by mass-to-charge ratio.',
   'Describe the four stages that take place in a mass spectrometer.\nThe mass spectrometer detects each isotope separately.'],
  ['Mass Spectrum', 'Noun',
   '質量スペクトル。質量分析計の出力グラフ。縦軸は相対存在比、横軸は質量電荷比。\nThe output graph of a mass spectrometer: relative abundance against mass-to-charge ratio.',
   'Use the mass spectrum to calculate the relative atomic mass of the element.\nThe mass spectrum shows two peaks.'],
  ['Mass-to-Charge Ratio', 'Noun',
   '質量電荷比。質量スペクトルの横軸にとる量。m/e（m/z）と書き、1価イオンではイオンの質量に等しい。\nThe quantity plotted on the horizontal axis of a mass spectrum, written m/e. For singly charged ions it equals the mass of the ion.',
   'The peak at m/e = 35 is due to the chlorine-35 ion.\nState what is meant by the mass-to-charge ratio.'],
  ['Molecular Ion', 'Noun',
   '分子イオン。試料分子が電子を1個だけ失って生じるイオン M⁺。最も大きい m/e のピークが相対分子質量を与える。\nThe ion M+ formed when a whole molecule loses just one electron; its peak gives the relative molecular mass.',
   'The molecular ion peak is at m/e = 46.\nIdentify the molecular ion in the mass spectrum.'],
  ['M+1 Peak', 'Noun',
   'M+1 ピーク。分子イオンピークより1だけ大きいところに現れる小さなピーク。炭素13に由来し、その高さから炭素数がわかる。\nThe small peak one unit above the molecular ion peak, caused by carbon-13; its relative height gives the number of carbon atoms.',
   'Use the M+1 peak to deduce the number of carbon atoms in the molecule.\nThe M+1 peak is about 1.1% as high as the M peak for each carbon atom.'],
  ['Carbon-13', 'Noun',
   '炭素13。天然に存在する炭素の重い同位体（約1.1%）。M+1 ピークの原因となる。\nThe heavy, naturally occurring isotope of carbon (about 1.1% of all carbon), which produces the M+1 peak.',
   'Carbon-13 accounts for about 1.1% of all carbon atoms.\nThe M+1 peak is caused by molecules containing one carbon-13 atom.'],
  ['Fragmentation', 'Noun',
   'フラグメンテーション。高エネルギー電子が共有結合を切り、分子が小さな陽イオンに分かれること。切れやすい結合がわかる。\nThe breaking of a molecule into smaller charged pieces when high-energy electrons break its covalent bonds.',
   'Fragmentation produces peaks at lower m/e values.\nSuggest the formula of the fragment responsible for the peak at m/e = 15.'],
  ['Deflection', 'Noun',
   '偏向。運動する荷電粒子の進路が磁場や電場で曲げられること。軽いイオンほど大きく曲がる。\nThe bending of a moving charged particle’s path by a magnetic or electric field. Lighter ions are deflected more.',
   'The amount of deflection depends on the mass-to-charge ratio.\nExplain why a neutron is not deflected by the magnetic field.'],
  ['Relative Abundance', 'Noun',
   '相対存在比。各同位体がどれだけ多く存在するかを百分率やピークの高さで表したもの。\nHow common each isotope is, given as a percentage or a peak height.',
   'Multiply each isotopic mass by its relative abundance.\nThe relative abundance of chlorine-35 is 75%.'],
  ['Ideal Gas Law', 'Noun',
   '理想気体の状態方程式。pV = nRT。圧力・体積・物質量・温度を結びつける。\npV = nRT — the equation linking the pressure, volume, amount and temperature of a gas.',
   'Use the ideal gas law to calculate the volume of the gas.\nThe ideal gas law requires the temperature in kelvin.'],
  ['Gas Constant', 'Noun',
   '気体定数。R = 8.31 J K⁻¹ mol⁻¹。理想気体の状態方程式に現れる定数。\nR = 8.31 J K⁻¹ mol⁻¹ — the constant in the ideal gas equation.',
   'Substitute the gas constant into pV = nRT.\nThe gas constant has units of J K⁻¹ mol⁻¹.'],
  ['Moles Equation', 'Noun',
   '物質量の式。moles = mass ÷ molar mass（n = m / M）。変形して m = n × M、M = m / n。\nmoles = mass ÷ molar mass, i.e. n = m / M.',
   'Rearrange the moles equation to find the mass.\nUse the moles equation to convert 8.0 g of oxygen into moles.'],
  ['Kelvin', 'Noun',
   'ケルビン。絶対温度の SI 単位、記号 K。0 K が絶対零度で、度記号はつけない。\nThe SI unit of absolute temperature, symbol K. 0 K is absolute zero; there is no degree sign.',
   'Give your answer in kelvin.\nRoom temperature is about 298 K.'],
  ['Celsius to Kelvin Conversion', 'Expression',
   'セルシウス温度からケルビンへの換算。K = °C + 273。pV = nRT を使う前に必ず変換する。\nK = °C + 273 — always convert before using pV = nRT.',
   'Apply the Celsius to Kelvin conversion before substituting into the equation.\nUsing the Celsius to Kelvin conversion, 25 °C becomes 298 K.'],
  ['Pascal', 'Noun',
   'パスカル。圧力の SI 単位、記号 Pa。1気圧 ≈ 100 000 Pa、1 kPa = 1000 Pa。\nThe SI unit of pressure, symbol Pa. 1 atmosphere ≈ 100 000 Pa.',
   'Convert the pressure into pascals.\nA pressure of 101 kPa is 101 000 Pa.'],
  ['Volume Units', 'Expression',
   '体積の単位。1 m³ = 1000 dm³ = 1 000 000 cm³、1 dm³ = 1 L = 1000 cm³。\n1 m3 = 1000 dm3 = 1 000 000 cm3; 1 dm3 = 1 litre = 1000 cm3.',
   'Convert the volume units into cubic metres before using pV = nRT.\nRemember the volume units: 24 dm3 is 24 000 cm3.'],
  ['Calculate', 'Verb',
   '計算せよ。数値を出す設問。計算過程を示し、単位と有効数字に注意する。\nProduce a number. Show your working, carry the units through, and quote a sensible number of significant figures.',
   'Calculate the relative atomic mass of the element.\nCalculate the mass of copper produced, giving your answer to three significant figures.'],
  ['Deduce', 'Verb',
   '推定せよ。与えられた情報から論理的に答えを導く。暗記した知識を答えるのではない。\nWork the answer out from the information you are given, using reasoning.',
   'Deduce the formula of the compound from the data in the table.\nDeduce, with a reason, which element it is.'],
  ['Define', 'Verb',
   '定義を述べよ。覚えた定義を正確な言い回しで書く。各節に配点がある。\nGive the exact, learned wording of a definition. Every clause carries a mark.',
   'Define the term first ionisation energy.\nDefine relative atomic mass.'],
  ['Explain', 'Verb',
   '説明せよ。観察だけでなく理由を述べる。because、so、therefore を使う。\nGive a reason, not just an observation.',
   'Explain why the first ionisation energy decreases down the group.\nExplain, in terms of intermolecular forces, why water has a high boiling point.'],
  ['Suggest', 'Verb',
   '考えを述べよ。既知の知識を未知の状況に応用する。答えが複数あり得る。\nApply what you know to an unfamiliar situation. There may be more than one acceptable answer.',
   'Suggest why the actual yield is less than the theoretical yield.\nSuggest a reason for the peak at m/e = 29.'],
];

var MATH_WORDS = [
  ['Quadratic Equation', 'Noun',
   '二次方程式。ax² + bx + c = 0（a ≠ 0）の形の方程式。因数分解、平方完成、解の公式で解く。\nAn equation of the form ax2 + bx + c = 0 with a ≠ 0.',
   'Solve the quadratic equation 2x2 – 5x + 2 = 0.\nShow that the quadratic equation has no real roots.'],
  ['Quadratic Formula', 'Noun',
   '解の公式。x = (–b ± √(b² – 4ac)) / 2a。根号の中に判別式が含まれる。\nx = (–b ± √(b2 – 4ac)) / 2a — solves any quadratic.',
   'Use the quadratic formula to find the roots, leaving your answer in surd form.\nThe quadratic formula contains the discriminant under the root sign.'],
  ['Discriminant', 'Noun',
   '判別式。b² – 4ac。二次方程式の実数解の個数を決める式。\nb2 – 4ac, the expression that decides how many real roots a quadratic has.',
   'Find the value of the discriminant.\nGiven that the equation has two distinct real roots, show that the discriminant is positive.'],
  ['Real Roots', 'Expression',
   '実数解。実数である解。判別式が0以上のとき二次方程式は実数解をもつ。\nSolutions that are real numbers. A quadratic has real roots when its discriminant is greater than or equal to zero.',
   'Show that the equation has no real roots.\nFind the range of values of k for which the equation has two real roots.'],
  ['Repeated Root', 'Noun',
   '重解。b² – 4ac = 0 のときの唯一の解。曲線は x 軸を横切らずに接する。\nThe single solution a quadratic has when b2 – 4ac = 0; the curve touches the x-axis instead of crossing it.',
   'Given that the equation has a repeated root, find the value of k.\nA repeated root means the curve touches the x-axis.'],
  ['Root', 'Noun',
   '解（根）。式の値を0にする x の値。f(x) = 0 の解であり、曲線の x 切片にあたる。\nA value of x that makes an expression zero — a solution of f(x) = 0, and an x-intercept of the curve.',
   'Find the roots of f(x) = 0.\nThe roots of the equation are the x-coordinates of the points where the curve crosses the x-axis.'],
  ['Coefficient', 'Noun',
   '係数。変数の累乗にかかる数。ax² の a、3x の 3。\nThe number multiplying a power of the variable — the a in ax2, the 3 in 3x.',
   'Write down the coefficient of x3 in the expansion.\nFind the coefficient of x2 in the binomial expansion.'],
  ['Constant', 'Noun',
   '定数。値は決まっているが未知の数で、文字で表す（a, b, c, k, p, q）。変化する変数と対になる語。\nA fixed but unknown number, written as a letter. Contrast a variable, which changes.',
   'Find the value of the constant k.\nGiven that a and b are constants, express y in terms of x.'],
  ['Critical Values', 'Expression',
   '臨界値。対応する方程式の解。数直線を区間に分け、どの区間が不等式を満たすかを調べる。\nThe roots of the corresponding equation; they divide the number line into regions to be tested against the inequality.',
   'Find the critical values of the inequality.\nThe critical values are x = –2 and x = 5.'],
  ['Inequality', 'Noun',
   '不等式。一方の式が他方より大きい・小さいことを表す文。解は1つの値ではなく値の集合になる。\nA statement that one expression is less than or greater than another. Solving one produces a set of values.',
   'Solve the inequality x2 – 4x – 5 > 0.\nGive the set of values of x that satisfy the inequality.'],
  ['Simultaneous Equations', 'Expression',
   '連立方程式。同時に成り立つ2つ以上の方程式。2曲線の交点を求める標準的な方法。\nTwo or more equations solved together — the standard way to find where two curves meet.',
   'Solve the simultaneous equations y = x2 – 3 and y = 2x.\nUse simultaneous equations to find the coordinates of the points of intersection.'],
  ['Completing the Square', 'Expression',
   '平方完成。ax² + bx + c を a(x + p)² + q の形に書き換える操作。頂点がわかり、厳密解が得られる。\nRewriting ax2 + bx + c in the form a(x + p)2 + q, which shows the turning point and gives an exact solution.',
   'Solve the equation by completing the square.\nBy completing the square, find the coordinates of the minimum point.'],
  ['Factorise', 'Verb',
   '因数分解せよ。式を括弧の積の形に書き直す。積が0なら各因数を順に0とおける。\nRewrite an expression as a product of brackets.',
   'Factorise x2 – 7x + 12 completely.\nFactorise the expression, and hence solve f(x) = 0.'],
  ['Expand', 'Verb',
   '展開せよ。括弧を外して掛け合わせる。因数分解の検算にも使う。\nMultiply out brackets. The standard way to check a factorisation is to expand it back.',
   'Expand and simplify (2x – 3)(x + 5).\nExpand your answer to check the factorisation.'],
  ['Factor Theorem', 'Noun',
   '因数定理。f(a) = 0 ならば (x – a) は f(x) の因数であり、逆も成り立つ。三次式を分解する標準手段。\nIf f(a) = 0 then (x – a) is a factor of f(x), and conversely.',
   'Use the factor theorem to show that (x – 2) is a factor of f(x).\nHence, using the factor theorem, factorise f(x) completely.'],
  ['Substitute', 'Verb',
   '代入せよ。文字を値や式に置き換える。因数定理や検算の土台になる操作。\nReplace a letter with a value or an expression.',
   'Substitute x = 3 into the equation.\nSubstitute your answer back into the original equation to check it.'],
  ['Binomial Expansion', 'Noun',
   '二項展開。(1 + x)ⁿ や (a + b)ⁿ を級数に展開すること。ふつうは指定された項までで止める。\nExpanding (1 + x)n or (a + b)n as a series, usually only as far as a stated term.',
   'Find the first four terms of the binomial expansion of (1 + 2x)8.\nUse the binomial expansion to estimate the value of 1.0025.'],
  ['Surd', 'Noun',
   '無理数の根号形。√2 や 3√5 のように、根号のまま厳密に書いた無理数。exact answer はしばしばこれを意味する。\nAn irrational root left in exact form, such as √2 or 3√5.',
   'Give your answer in surd form.\nSimplify the surd, rationalising the denominator.'],
  ['Differentiation', 'Noun',
   '微分。y の x に対する変化率 dy/dx を求めること。各点における曲線の傾きにあたる。\nFinding dy/dx, the rate of change of y with respect to x — the gradient of the curve at each point.',
   'Use differentiation to find dy/dx.\nBy differentiation, find the coordinates of the stationary point.'],
  ['Integration', 'Noun',
   '積分。微分の逆の操作。曲線の下の面積を求める道具でもある。\nThe reverse of differentiation; also the tool for finding the area under a curve.',
   'Use integration to find the area of the shaded region.\nIntegration of dy/dx gives back the equation of the curve.'],
  ['Constant of Integration', 'Expression',
   '積分定数。不定積分に必ず加える + c。定数を微分すると0になるため。\nThe + c that must be added to every indefinite integral, because differentiating any constant gives zero.',
   'Do not forget the constant of integration.\nUse the given point to find the constant of integration.'],
  ['Area Under a Curve', 'Expression',
   '曲線の下の面積。領域を挟む2つの x の値の間で定積分して求める。\nFound by definite integration between the two x values that bound the region.',
   'Find the area under the curve between x = 1 and x = 4.\nThe area under the curve represents the distance travelled.'],
  ['Bounded Region', 'Expression',
   '囲まれた領域。指定されたグラフどうしで囲まれた部分。ふつう図で斜線が引かれている。\nThe enclosed area between named graphs, usually shaded in the figure.',
   'Find the exact area of the bounded region R.\nThe bounded region is finite, so the integral converges.'],
  ['Rate of Change', 'Expression',
   '変化率。ある量が別の量に対してどれだけ速く変化するか。導関数に現実的な意味を与えたもの。\nHow fast one quantity changes with respect to another — a derivative given a real-world meaning.',
   'Find the rate of change of the volume with respect to time.\nInterpret dP/dt as a rate of change in this context.'],
  ['Second Derivative', 'Noun',
   '二次導関数。d²y/dx²。導関数をもう一度微分したもの。停留点の種類の判定に使う（正なら極小、負なら極大）。\nd2y/dx2, the derivative of the derivative. Used to classify a stationary point.',
   'Find the second derivative and hence determine the nature of the stationary point.\nThe second derivative is negative, so the point is a maximum.'],
  ['Find', 'Verb',
   '求めよ。過程を示して答えを出す。最も多い指示語で、方法にも配点がある。\nProduce the answer with working; method marks are available, so show the route.',
   'Find the value of x.\nFind, in terms of k, the coordinates of the turning point.'],
  ['Show That', 'Expression',
   '〜を示せ。答えは与えられており、そこへ至る完全な論証を書く。書かれた答えだけでは点にならない。\nYou are given the answer; your job is to produce a complete argument that reaches it.',
   'Show that the equation can be written as x2 – 6x + 4 = 0.\nShow that the area of the region is 12.'],
  ['Prove', 'Verb',
   '証明せよ。show that よりも厳密さが求められ、各段階の理由を述べて論理を見せる。\nA show that with a higher standard of rigour: state the reason for each step.',
   'Prove that the sum of two odd numbers is even.\nProve, by counter-example, that the statement is false.'],
  ['Verify', 'Verb',
   '確かめよ。与えられた値を代入して成り立つことを示す。導出は不要。\nSubstitute the given value in and show it works. You do not have to derive it.',
   'Verify that x = 2 is a solution of the equation.\nVerify that the point lies on the curve.'],
  ['Solve', 'Verb',
   '解け。等式や不等式を満たす未知数の値をすべて求める。区間が指定されていればその中で。\nFind every value of the unknown that satisfies the equation or inequality, within the stated interval.',
   'Solve the equation for 0 ≤ x < 360°.\nSolve the inequality, giving your answer in set notation.'],
  ['State', 'Verb',
   '述べよ。短く事実だけを答える。導出も説明も計算も不要。\nGive a short, factual answer. No derivation, no explanation, no working.',
   'State the coordinates of the turning point.\nState the equation of the asymptote.'],
  ['Write Down', 'Expression',
   '書き出せ。すでに出ている内容から直ちに従う答えを、1行で書く。計算不要。\nThe answer should follow immediately from what you already have. One line, no working.',
   'Write down the value of f(0).\nWrite down the equation of the line of symmetry.'],
  ['Sketch', 'Verb',
   '概形を描け。正確な作図ではなく、グラフの形を描く。切片・漸近線・極値などの特徴に配点がある。\nDraw the shape of the graph, not an accurate plot. Marks come from the features you label.',
   'Sketch the curve, showing the coordinates of the points where it crosses the axes.\nOn the same axes, sketch the graph of y = f(x) + 3.'],
  ['Draw', 'Verb',
   '作図せよ。与えられた目盛りを使い、方眼上に正確な図をかく。sketch とは違い測って描く。\nProduce an accurate diagram on the grid supplied, using the scale given.',
   'Draw the box plot on the grid provided.\nDraw a histogram to represent the data.'],
  ['Determine', 'Verb',
   '判定せよ。計算結果を条件と比べて結論を出し、言葉で答える。\nReach a decision and justify it; compare a calculated value against a stated condition, then answer in words.',
   'Determine whether the point lies inside the circle.\nDetermine the nature of the stationary point.'],
  ['Express', 'Verb',
   '〜の形で表せ。指定された形に書き直す。形は問題文に印刷されており、それに正確に合わせる。\nRewrite the given expression in a specified form; your answer must match it exactly.',
   'Express 4x2 + 8x + 3 in the form a(x + b)2 + c.\nExpress your answer in the form p + q√3.'],
  ['Interpret', 'Verb',
   '解釈せよ。数値が問題の文脈で何を意味するかを、その単位と言葉で説明する。\nExplain what a number means in the context of the question, in the units and language of the real situation.',
   'Interpret the value of the gradient in the context of the model.\nInterpret the meaning of the constant a.'],
  ['Complete', 'Verb',
   '完成させよ。一部が与えられた表・図・グラフの空欄を埋める。\nFill in the missing entries of a table, diagram or graph that has been partly done for you.',
   'Complete the table of values.\nComplete the tree diagram.'],
  ['Give a Reason', 'Expression',
   '理由を述べよ。言葉で根拠を加える。state や determine に付くことが多く、独立した配点がある。\nAdd a justification in words; always worth a separate mark.',
   'State, giving a reason, whether the model is suitable.\nGive a reason for your answer.'],
  ['Hence', 'Adv',
   'これを用いて。前の小問の結果を使えという指示。無関係な別解では点にならないことがある。\nUse the result of the previous part. Marks are tied to that link.',
   'Hence find the exact value of the integral.\nHence, or otherwise, solve the equation.'],
  ['Correct To', 'Expression',
   '〜の精度で。値に精度を指定する言い回し（correct to 3 significant figures など）。\nThe phrase that attaches an accuracy to a stated value.',
   'Give your answer correct to 3 significant figures.\nThe length is 4.62 m, correct to two decimal places.'],
  ['Decimal Places', 'Expression',
   '小数点以下の桁数。指定されたときは既定の有効数字3桁より優先される。\nAn accuracy instruction counted after the decimal point, overriding the default 3 significant figures.',
   'Give your answer to two decimal places.\nRound the final value to one decimal place.'],
  ['Significant Figures', 'Expression',
   '有効数字。試験全体の既定の精度。途中では丸めず、最後にだけ丸める。\nThe default accuracy of the whole paper. Round only at the very end.',
   'Give your answer to three significant figures.\nKeep full accuracy until the end, then round to significant figures.'],
  ['Exact Answer', 'Expression',
   '厳密な値。根号・分数・π・対数のまま答える。小数に直してはいけない。\nLeave the answer as a surd, fraction, π or logarithm. Do not convert to a decimal.',
   'Give your answer as an exact answer in terms of π.\nFind the exact answer, leaving it in surd form.'],
  ['Give Your Answer in Simplest Form', 'Expression',
   '最も簡単な形で答えよ。共通因数を約分し、分母を有理化し、同類項をまとめる。\nCancel every common factor, rationalise denominators, and collect terms.',
   'Give your answer in simplest form.\nSimplify fully, giving your answer in simplest form.'],
  ['Given That', 'Expression',
   '〜であるとき。前提として使ってよい情報を導入する。ひとつひとつが別の手がかりであり、配点にもなる。\nIntroduces the information you are allowed to assume. Each given that is a separate piece of data.',
   'Given that the curve passes through (2, 5), find the value of k.\nGiven that x > 0, solve the equation.'],
  ['In Terms Of', 'Expression',
   '〜を用いて表せ。指定された文字だけで答えを書く。小数や他の変数は使わない。\nYour answer must be written using the named letters only.',
   'Find the area in terms of x.\nExpress y in terms of x and k.'],
  ['Let', 'Verb',
   '〜とおく。問題が名前をつけていない量に自分で文字を割り当てる。使う前に単位まで含めて一文で定義する。\nHow you introduce your own letter for a quantity the question has not named.',
   'Let x be the length of the shorter side, in metres.\nLet n be the number of terms in the series.'],
  ['The Set of Values', 'Expression',
   '値の集合。不等式の答え。ひとつの数ではなく範囲であり、不等号を使って書く。\nThe answer to an inequality: not a single number but a range, written with inequality signs.',
   'Find the set of values of x for which the curve is above the line.\nGive the set of values in set notation.'],
  ['The Range of Values', 'Expression',
   '定数の取り得る範囲。未知数が変数ではなく係数のときに使い、条件を満たす定数の範囲を答える。\nUsed when the unknown is a parameter rather than the variable — the values of a constant for which a condition holds.',
   'Find the range of values of k for which the equation has no real roots.\nState the range of values of a.'],
  ['Using the Model', 'Expression',
   'モデルを用いて。与えられた仮定の範囲内で答えよという指示。後の小問でモデルの限界を問われることが多い。\nAnswer inside the assumptions you were given; the phrase also warns that the model is not reality.',
   'Using the model, find the population after 10 years.\nUsing the model, estimate the temperature after 5 minutes.'],
  ['Where k Is a Constant to Be Found', 'Expression',
   '（k は求めるべき定数とする）。答えの形は与えられており、空いた文字の値を求めるのが課題。最後に k = … と明記する。\nThe structure of the answer is given; finding the value of the blank letter is the task.',
   'Show that the equation can be written as y = kx2, where k is a constant to be found.\nAlways finish by writing k = … explicitly.'],
  ['Curve', 'Noun',
   '曲線。方程式のグラフ。ふつう C, C₁, C₂ のように大文字で名前がつけられる。\nThe graph of an equation, usually labelled with a capital letter: C, C1, C2.',
   'The curve C has equation y = x3 – 4x.\nFind the coordinates of the point where the curve crosses the y-axis.'],
  ['Equation of a Curve', 'Expression',
   '曲線の方程式。その曲線上の x と y が満たす関係式。「find an equation for C」は標準形で書けという意味。\nThe relation between x and y that the curve satisfies.',
   'Find an equation of the curve, giving your answer in the form y = f(x).\nWrite down the equation of the curve after the translation.'],
  ['Coordinate Axes', 'Expression',
   '座標軸。x 軸と y 軸。「where the curve cuts the coordinate axes」は x 切片と y 切片のこと。\nThe x-axis and the y-axis.',
   'Show where the curve cuts the coordinate axes.\nLabel the points of intersection with the coordinate axes.'],
  ['Gradient', 'Noun',
   '傾き。直線の傾き、または曲線の各点での傾き。曲線では導関数の値にあたる。\nThe steepness of a line, or of a curve at a point; for a curve it is the value of the derivative there.',
   'Find the gradient of the curve at the point (2, 5).\nThe gradient of the line is –3.'],
  ['Tangent', 'Noun',
   '接線。曲線に1点で接し、その点で曲線と同じ傾きをもつ直線。\nA line that touches a curve at a point and has the same gradient as the curve there.',
   'Find an equation of the tangent to the curve at P.\nThe tangent to a circle is perpendicular to the radius at the point of contact.'],
  ['Asymptote', 'Noun',
   '漸近線。曲線が限りなく近づくが決して達しない直線。数ではなく方程式（x = –3、y = 0）で答える。\nA line the curve approaches but never reaches. Given as an equation, never as a number.',
   'Write down the equations of the asymptotes.\nThe curve has an asymptote at y = 0.'],
  ['Stationary Point', 'Noun',
   '停留点。傾きが0になる曲線上の点（dy/dx = 0）。極大・極小・変曲点のいずれか。\nA point on a curve where the gradient is zero. It may be a maximum, a minimum or a point of inflection.',
   'Find the coordinates of the stationary point.\nDetermine the nature of each stationary point.'],
  ['Stationary Value', 'Expression',
   '停留値。停留点における関数の値（起こる x 座標ではなく y の値）。\nThe value of the function at a stationary point — as opposed to the x coordinate where it happens.',
   'Find the stationary value of y.\nState whether the stationary value is a maximum or a minimum.'],
  ['Minimum and Maximum', 'Expression',
   '極小と極大。2種類の転回点。二次導関数の符号で判定する（正なら極小、負なら極大）。\nThe two kinds of turning point, confirmed by the second derivative: positive → minimum, negative → maximum.',
   'Find the coordinates of the minimum and maximum points.\nShow that the point is a minimum.'],
  ['Point of Intersection', 'Expression',
   '交点。2つのグラフが交わる点。連立して解くことで求める。\nWhere two graphs meet. Found by solving their equations simultaneously.',
   'Find the coordinates of the points of intersection of the line and the curve.\nAt the point of intersection the two equations are equal.'],
  ['Figure', 'Noun',
   '図。問題に印刷された番号つきの図（Figure 1 など）。何を示しているか先に読む。\nThe numbered diagram printed with the question: Figure 1, Figure 2.',
   'Figure 2 shows the curve C and the line l.\nThe shaded region in Figure 1 is bounded by the curve and the x-axis.'],
  ['Circle', 'Noun',
   '円。中心から一定の距離にある点の集合。方程式は (x – a)² + (y – b)² = r²。\nThe set of points a fixed distance from a centre; its equation is (x – a)2 + (y – b)2 = r2.',
   'Find an equation of the circle with centre (3, –1) and radius 5.\nShow that the line is a tangent to the circle.'],
  ['Centre and Radius', 'Expression',
   '中心と半径。円の方程式からそのまま読み取る。接点への半径は接線と垂直。\nRead straight off the circle equation: centre (a, b), radius r.',
   'Write down the centre and radius of the circle.\nFind the centre and radius by completing the square.'],
  ['Perpendicular', 'Adj',
   '垂直な。直交する。2直線では傾きの積が −1、2ベクトルでは内積が0になる。\nAt right angles. For two lines, the product of their gradients is –1.',
   'Find an equation of the line perpendicular to l passing through P.\nShow that OA is perpendicular to OB.'],
  ['Magnitude', 'Noun',
   '大きさ。向きを無視したベクトルの長さ。|ai + bj| = √(a² + b²)。力ならニュートン数。\nThe size of a vector, ignoring direction: |ai + bj| = √(a2 + b2).',
   'Find the magnitude of the resultant force.\nCalculate the magnitude of the vector 3i – 4j.'],
  ['Position Vector', 'Noun',
   '位置ベクトル。定点 O からある点へのベクトル。その点の座標そのものでもある。\nThe vector from a fixed origin O to a point; it doubles as the coordinates of that point.',
   'The point A has position vector 2i + 5j.\nFind the position vector of the midpoint of AB.'],
  ['Fixed Origin', 'Expression',
   '定点（原点）。すべての位置ベクトルを測る基準点 O。\nThe reference point O that all position vectors are measured from.',
   'The particle moves relative to a fixed origin O.\nPosition vectors are measured from the fixed origin.'],
  ['Unit Vectors i and j', 'Expression',
   '単位ベクトル i と j。x 方向・y 方向の長さ1の直交ベクトル。平面のベクトルはこの組合せで書く。\nPerpendicular vectors of length 1 along the x and y directions.',
   'Give your answer in terms of the unit vectors i and j.\nThe velocity is (3i + 4j) m s–1.'],
  ['Logarithm', 'Noun',
   '対数。累乗の逆。log_a x は、a を何乗すると x になるかを表す。\nThe inverse of a power: log to base a of x is the power to which a must be raised to give x.',
   'Take logarithms of both sides.\nSolve the equation, giving your answer as a logarithm.'],
  ['Log Laws', 'Expression',
   '対数法則。log xy = log x + log y、log(x/y) = log x – log y、log xⁿ = n log x。積を和に変える。\nlog xy = log x + log y · log (x/y) = log x – log y · log xn = n log x.',
   'Use the log laws to write the expression as a single logarithm.\nApply the log laws to bring the power down.'],
  ['e and the Natural Exponential', 'Expression',
   'e と自然指数関数。定数 e ≈ 2.718。eˣ は微分しても自分自身になるため、成長・減衰モデルに必ず現れる。\nThe constant e ≈ 2.718; the function ex is its own derivative.',
   'Differentiate y = e2x with respect to x.\nThe natural exponential appears in every growth and decay model.'],
  ['Exponential Model', 'Expression',
   '指数モデル。y = abˣ や y = Aeᵏᵗ で表される現実の状況。変化率が現在量に比例する。\nA real situation modelled by y = abx or y = Aekt, where the rate of change is proportional to the current amount.',
   'Using the exponential model, find the value of P when t = 10.\nExplain why an exponential model is suitable here.'],
  ['Log-linear Graph', 'Expression',
   '片対数グラフ。log P を x に対してプロットすると指数関係が直線になり、傾きと切片から定数が求まる。\nPlotting log P against x turns an exponential relationship into a straight line.',
   'The log-linear graph has gradient 0.3 and intercept 1.2.\nUse the log-linear graph to estimate the values of a and b.'],
  ['Acceleration', 'Noun',
   '加速度。速度の変化率。単位は m s⁻²。v を微分して得られ、F = ma で力と結びつく。\nThe rate of change of velocity, in m s–2. Found by differentiating v, and linked to force by F = ma.',
   'Find the acceleration of the particle at time t = 3 s.\nThe car accelerates uniformly at 2 m s–2.'],
  ['Deceleration', 'Noun',
   '減速度。負の加速度。deceleration の語のあとは正の数で答える。\nSlowing down — a negative acceleration. Quote it as a positive number after the word deceleration.',
   'Find the deceleration of the train.\nThe cyclist decelerates at 1.5 m s–2.'],
  ['Acceleration Due to Gravity', 'Expression',
   '重力加速度。この試験で用いる値は g = 9.8 m s⁻²。\ng = 9.8 m s–2, the value specified for this paper.',
   'Take the acceleration due to gravity to be 9.8 m s–2.\nThe ball falls freely under the acceleration due to gravity.'],
  ['Velocity', 'Noun',
   '速度。向きをもつ速さ。記号 v、単位 m s⁻¹。時間で微分すると加速度になる。\nSpeed with direction, written v and measured in m s–1.',
   'Find the velocity of the particle after 4 seconds.\nThe velocity is negative, so the particle is moving in the opposite direction.'],
  ['At Rest', 'Expression',
   '静止している。速度が0の状態。comes to rest は運動の終わりを示す。\nNot moving — velocity zero. Comes to rest marks the end of the motion.',
   'The particle is initially at rest.\nFind the time at which the car comes to rest.'],
  ['Instantaneous Rest', 'Expression',
   '瞬間的な静止。v = 0 だが運動は続く瞬間。区間内にあると移動距離と変位が一致しない。\nA moment when v = 0 but the motion continues; distance travelled is then not the same as displacement.',
   'Show that the particle is at instantaneous rest when t = 2.\nAt instantaneous rest the velocity changes sign.'],
  ['Particle', 'Noun',
   '質点。質量はあるが大きさをもたない点として扱う物体。回転や寸法を無視できる。\nA body treated as a single point with mass but no size.',
   'The box is modelled as a particle.\nA particle of mass 3 kg rests on a smooth plane.'],
  ['Modelled As', 'Expression',
   '〜としてモデル化される。単純化の仮定を導入する言い回し。仮定はすべて現実とのずれの原因になる。\nThe phrase that introduces each simplifying assumption.',
   'The car is modelled as a particle.\nState one limitation of the box being modelled as a particle.'],
  ['Smooth', 'Adj',
   'なめらかな。摩擦のない。なめらかな面は運動方向に力を及ぼさない。\nFrictionless. A smooth surface exerts no force along the direction of motion.',
   'The plane is smooth, so friction can be ignored.\nThe pulley is modelled as smooth and light.'],
  ['Light Rod', 'Expression',
   '軽い棒。質量が無視でき、変形しないとみなす連結棒。両端で張力が等しい。\nA connecting rod modelled as having no mass and being rigid, so the tension is the same at both ends.',
   'The two particles are joined by a light rod.\nBecause the rod is light, the tension is the same throughout.'],
  ['Tension', 'Noun',
   '張力。ひも・ロープ・けん引棒に生じる引く力。T ニュートンと書く。\nThe pulling force in a string, rope or towbar, written T newtons.',
   'Find the tension in the string.\nThe tension in the towbar is 250 N.'],
  ['Driving Force', 'Expression',
   '駆動力。エンジンが生み出す前向きの力。運動方向に働く。\nThe forward force produced by an engine, acting along the direction of motion.',
   'The driving force of the engine is 2000 N.\nFind the magnitude of the driving force.'],
  ['Resistance to Motion', 'Expression',
   '運動への抵抗。摩擦と空気抵抗を合わせた抵抗力。ふつう一定としてニュートンで与えられる。\nThe total opposing force — friction plus air resistance — usually modelled as constant.',
   'The resistance to motion is modelled as a constant force of 400 N.\nFind the total resistance to motion.'],
  ['Newton', 'Noun',
   'ニュートン。力の SI 単位、記号 N。1 N は質量1 kg に 1 m s⁻² の加速度を与える力。\nThe SI unit of force, symbol N. One newton accelerates 1 kg at 1 m s–2.',
   'Give your answer in newtons.\nThe weight of the particle is 29.4 N.'],
  ['Uniformly', 'Adv',
   '一定の割合で。accelerates uniformly は加速度が一定という意味で、速度時間グラフでは直線になる。\nAt a constant rate. Accelerates uniformly means constant acceleration.',
   'The train accelerates uniformly from rest.\nThe particle decelerates uniformly to rest in 8 seconds.'],
  ['Speed-Time Graph', 'Expression',
   '速さ時間グラフ。縦軸が速さ、横軸が時間。傾きが加速度、面積が移動距離を表す。\nSpeed on the vertical axis, time on the horizontal. The gradient is the acceleration and the area is the distance travelled.',
   'Sketch a speed-time graph for the motion of the car.\nUse the speed-time graph to find the total distance travelled.'],
  ['Distance-Time Graph', 'Expression',
   '距離時間グラフ。縦軸が距離、横軸が時間。傾きが速さ。等速なら直線、加速していれば曲線になる。\nDistance on the vertical axis, time on the horizontal; its gradient is the speed.',
   'The distance-time graph is a straight line, so the speed is constant.\nFind the speed from the gradient of the distance-time graph.'],
  ['Function Notation', 'Expression',
   '関数記法。f(x) は x の関数を表す。x に式を代入すると（f(⅓x) など）グラフが変形する。\nf(x) names a function of x; substituting an expression for x transforms it.',
   'The function f is defined by f(x) = 2x2 – 3.\nUsing function notation, write down the value of f(–1).'],
  ['Vector Notation', 'Expression',
   'ベクトル記法。PQ の上に矢印で P から Q へのベクトル。i, j は直交単位ベクトル。印刷では太字、手書きでは下線。\nPQ with an arrow is the vector from P to Q; i and j are perpendicular unit vectors. Vectors are printed in bold.',
   'Write the displacement in vector notation.\nIn vector notation, the force is (4i – 3j) N.'],
  ['Inequality Symbols', 'Expression',
   '不等号。< 小なり、> 大なり、⩽ 以下、⩾ 以上、≠ 等しくない。\n< less than · > greater than · ⩽ less than or equal to · ⩾ greater than or equal to · ≠ not equal to.',
   'Write your answer using inequality symbols.\nThe inequality symbols show that x is between –2 and 5.'],
  ['Therefore', 'Adv',
   'したがって。記号 ∴。上の行から論理的に導かれる行であることを示す。\nThe symbol ∴, read therefore. It marks the line that follows logically from the ones above.',
   'The discriminant is negative; therefore the equation has no real roots.\nWrite ∴ before your conclusion.'],
  ['Because', 'Adv',
   'なぜならば。記号 ∵。直前の行の根拠を導入する。\nThe symbol ∵, read because or since. It introduces the justification for the step just written.',
   'The curve has a minimum, because the second derivative is positive.\nUse ∵ to introduce the reason for the step.'],
  ['Implies', 'Verb',
   '〜を意味する。記号 ⇒。⇔ は「必要十分」で、両方向に成り立つことを表す。\nThe symbol ⇒, read implies or so. ⇔ means if and only if — the step works in both directions.',
   'x2 = 9 implies x = 3 or x = –3.\nUse ⇔ only when the step is reversible.'],
  ['Q.E.D.', 'Acronym',
   'Q.E.D.（quod erat demonstrandum、「これが示されるべきことであった」）。証明の終わりに書き、求める結果に達したことを示す。\nLatin quod erat demonstrandum — "which was to be demonstrated". Written at the end of a proof.',
   'Write Q.E.D. at the end of the proof.\nThe result is proved, Q.E.D.'],
  ['Hypothesis Test', 'Expression',
   '仮説検定。母集団についての主張を棄却できるだけの証拠が標本にあるかを判断する正式な手続き。\nA formal procedure for deciding whether sample evidence is strong enough to reject a claim about a population.',
   'Carry out a hypothesis test at the 5% level of significance.\nState the conclusion of the hypothesis test in context.'],
  ['Null and Alternative Hypotheses', 'Expression',
   '帰無仮説と対立仮説。H₀ は検定する値、H₁ は疑っている内容。「has decreased」なら片側検定の H₁ になる。\nH0 states the value being tested; H1 states what you suspect instead.',
   'Write down the null and alternative hypotheses.\nH0: p = 0.4, H1: p < 0.4.'],
  ['Level of Significance', 'Expression',
   '有意水準。H₀ を棄却する基準となる確率（ここでは5%）。求めた確率がこれより小さければ有意。\nThe threshold probability for rejecting H0. If your probability is below it, the evidence is significant.',
   'Use a 5% level of significance.\nThe probability is less than the level of significance, so reject H0.'],
  ['p-value', 'Noun',
   'p 値。H₀ が正しいと仮定したとき、観測された結果以上に極端な値が出る確率。有意水準と比べる。\nThe probability of getting a result at least as extreme as the observed one, assuming H0 is true.',
   'Find the p-value for this test.\nThe p-value is 0.032, which is less than 0.05.'],
  ['Binomial Distribution', 'Expression',
   '二項分布。X ~ B(n, p)。成功確率 p の独立な試行を n 回行うときの分布。\nX ~ B(n, p) — n independent trials, each succeeding with probability p.',
   'The random variable X follows a binomial distribution B(20, 0.3).\nState two conditions for a binomial distribution to be a suitable model.'],
  ['Probability Distribution', 'Expression',
   '確率分布。確率変数の取り得るすべての値とその確率を示した表または規則。確率の合計は1になる。\nA table or rule listing every possible value of a random variable with its probability; they must sum to 1.',
   'Complete the probability distribution table.\nShow that the probabilities in the probability distribution sum to 1.'],
  ['Random Variable', 'Expression',
   '確率変数。値が偶然によって決まる量。大文字で表し、その具体的な値は小文字で書く。\nA quantity whose value depends on chance, written with a capital letter; its particular values use the small letter.',
   'The random variable X represents the number of heads.\nFind P(X = 3) for the random variable X.'],
  ['Histogram', 'Noun',
   'ヒストグラム。連続量の度数分布図で、面積が度数を表すため縦軸は度数密度になる。\nA diagram for grouped continuous data where area represents frequency, so the vertical axis is frequency density.',
   'Draw a histogram to represent these data.\nUse the histogram to estimate the number of values above 30.'],
  ['Frequency Density', 'Expression',
   '度数密度。度数 ÷ 階級幅。ヒストグラムの各棒の高さ。\nfrequency ÷ class width — the height of each bar on a histogram.',
   'Calculate the frequency density for each class.\nThe vertical axis shows frequency density, not frequency.'],
  ['Box and Whisker Plot', 'Expression',
   '箱ひげ図。最小値・第1四分位数・中央値・第3四分位数・最大値を示す図。方眼上に正確に描く。\nA diagram showing minimum, lower quartile, median, upper quartile and maximum.',
   'Draw a box and whisker plot for the data.\nCompare the two box and whisker plots.'],
  ['Median', 'Noun',
   '中央値。データを順に並べたときの真ん中の値。箱ひげ図では箱の中の線。\nThe middle value when the data are put in order.',
   'Find the median of the data.\nThe median is shown by the line inside the box.'],
  ['Interquartile Range', 'Expression',
   '四分位範囲。第3四分位数から第1四分位数を引いた値。中央50%の散らばりを表し、箱の幅にあたる。\nUpper quartile minus lower quartile — the spread of the middle 50%.',
   'Calculate the interquartile range.\nThe interquartile range is a measure of spread that ignores outliers.'],
  ['Range', 'Noun',
   '範囲。最大値から最小値を引いた値。最小値と組み合わせれば最大値がわかる。\nLargest value minus smallest value.',
   'Find the range of the data.\nThe range is 18, and the smallest value is 4.'],
  ['Summary Statistics', 'Expression',
   '要約統計量。中央値・範囲・四分位数など、データを短く表す数値の組。生データの代わりに与えられることが多い。\nA short set of numbers describing a data set — median, range, quartiles.',
   'The summary statistics for the data are given in the table.\nUse the summary statistics to draw a box plot.'],
  ['Large Data Set', 'Expression',
   '大規模データセット。Edexcel が学習を前提とする実際の気象データ（Camborne、Hurn など）。背景知識が問われる。\nThe real weather data set that Edexcel expects you to have studied.',
   'The data come from the large data set.\nUsing your knowledge of the large data set, suggest why the value is unusual.'],
  ['Sine Rule', 'Noun',
   '正弦定理。a / sin A = b / sin B = c / sin C。1辺とその対角がわかっているときに使う。\na / sin A = b / sin B = c / sin C — used when you have a side and its opposite angle.',
   'Use the sine rule to find the length of BC.\nApply the sine rule to find angle ABC.'],
  ['Cosine Rule', 'Noun',
   '余弦定理。a² = b² + c² – 2bc cos A。3辺、または2辺とその間の角がわかっているときに使う。\na2 = b2 + c2 – 2bc cos A — used with three sides, or two sides and the angle between them.',
   'Use the cosine rule to find angle BAC.\nApply the cosine rule to find the third side of the triangle.'],
  ['Trigonometric Identity', 'Expression',
   '三角恒等式。すべての角で成り立つ関係式（tan θ = sin θ / cos θ、sin²θ + cos²θ = 1）。1つの関数に書き換えるのに使う。\nA relation true for every angle, used to rewrite an equation in one function only.',
   'Use a trigonometric identity to write the equation in terms of sin θ only.\nProve the trigonometric identity.'],
  ['Solve in an Interval', 'Expression',
   '区間内で解け。三角方程式は解が無限にあるため範囲が指定される。その中の解をすべて求める。\nTrigonometric equations have infinitely many solutions, so the question restricts the range. Find every solution inside it.',
   'Solve the equation in the interval 0 ≤ x < 360°.\nFind all the solutions in the given interval.'],
  ['Angle Notation', 'Expression',
   '角の表し方。3文字で角を表し、真ん中の文字が頂点。angle BDC は D における角。\nThree letters name an angle, with the vertex in the middle: angle BDC is the angle at D.',
   'Find the size of angle BDC.\nAngle notation puts the vertex in the middle.'],
  ['Triangle', 'Noun',
   '三角形。3つの頂点の名前で表す（triangle ABD）。文中に追加の幾何学的条件が書かれていることに注意。\nNamed by its three vertices: triangle ABD.',
   'In triangle ABD, AB = 7 cm.\nFind the area of triangle ABC.'],
  ['Method', 'Noun',
   '方法（解法）。とった数学的な筋道。計算を間違えても正しい方法には M の配点がつく。\nThe mathematical route you took. Method marks (M) are awarded for a correct approach even when the arithmetic goes wrong.',
   'Show your method clearly.\nMethod marks are available even if the final answer is wrong.'],
  ['Show All Stages of Your Working', 'Expression',
   '過程をすべて示せ。この試験の基本指示であり、電卓で解けてしまう問題では明示的な警告でもある。配点は道筋につく。\nThe standing instruction of the paper: marks are attached to the route, not only to the destination.',
   'Show all stages of your working.\nIn this question you must show all stages of your working.'],
  ['Communication', 'Noun',
   '伝わる書き方。他の人が追えるように解答を書くこと。明確な手順、正しい記法、単位、図、そして結論の文。\nWriting your solution so another mathematician can follow it: clear steps, correct notation, units, diagrams and a written conclusion.',
   'Marks are given for communication as well as for the answer.\nGood communication means another reader can follow every step.'],
  ['Conclusion', 'Noun',
   '結論。問われたとおりに答える最後の一文。文脈と単位を添えて書く。\nThe closing sentence that answers the question as it was asked, in context and with units.',
   'Write a conclusion in the context of the question.\nThere is no conclusion, so the final mark is lost.'],
  ['Check by Substitution', 'Expression',
   '代入による検算。得た答えを元の式に戻して成り立つか確かめること。最も手軽に評価を上げる方法。\nPutting your answer back into the original equation to confirm it.',
   'Check by substitution that x = 4 satisfies the equation.\nA quick check by substitution catches most arithmetic slips.'],
  ['Marks in Brackets', 'Expression',
   '括弧内の配点。(2)、(4) のような小問末の数字。採点者が期待する要点の数と、かける時間の目安を示す。\nThe number after each part tells you how many creditable points the examiner expects, and how long to spend.',
   'The marks in brackets show that two points are expected.\nUse the marks in brackets to judge the length of your answer.'],
  ['Alpha, Beta and Gamma', 'Expression',
   'アルファ・ベータ・ガンマ。宿題の評価。その1回の答案に現れた内容を表すもので、書いた人自身の能力を表すものではない。\nThe homework feedback grades. They describe the evidence in one piece of work, not you as a mathematician.',
   'The work was graded Beta because the conclusion was missing.\nAlpha, Beta and Gamma describe the work, not the mathematician.'],
];

/* --- The import ----------------------------------------------------------- */

/** Creates the folder if it is not there, whatever case its name is in. */
function ensureFolder_(name) {
  var folders = listFolders_();
  for (var i = 0; i < folders.length; i++) {
    if (folders[i].name.toLowerCase() === name.toLowerCase()) return folders[i];
  }
  var created = createFolder_(name);
  Logger.log('Created folder "%s".', name);
  return created;
}

/** Key for "this word is already in this folder". */
function wordKey_(folder, word) {
  return folder.toLowerCase() + '\n' + word.toLowerCase();
}

function addALevelWords() {
  var sheet = getSheet_();
  var schema = ensureHeaders_(sheet);
  var width = schema.width;

  var chem = ensureFolder_(CHEM_FOLDER);
  var math = ensureFolder_(MATH_FOLDER);

  // What is already there, so a second run adds nothing twice.
  var seen = {};
  var existing = listWords_();
  for (var e = 0; e < existing.length; e++) {
    seen[wordKey_(existing[e].folder || '', existing[e].word)] = true;
  }

  var now = new Date().toISOString();
  var rows = [];
  var counts = {};
  var skipped = 0;

  var batches = [[chem.name, CHEM_WORDS], [math.name, MATH_WORDS]];
  for (var b = 0; b < batches.length; b++) {
    var folder = batches[b][0];
    var list = batches[b][1];

    for (var i = 0; i < list.length; i++) {
      var entry = list[i];
      if (seen[wordKey_(folder, entry[0])]) {
        skipped += 1;
        continue;
      }
      seen[wordKey_(folder, entry[0])] = true;

      // Straight through the same validation every saved word goes through,
      // so a typo here fails now rather than on the device later.
      var fields = validate_({
        word: entry[0], pos: entry[1], definition: entry[2], note: entry[3],
        color: 'default', folder: folder, status: ''
      });
      rows.push(wordToRow_(buildRecord_(fields, Utilities.getUuid(), now, now), schema.map, width));
      counts[folder] = (counts[folder] || 0) + 1;
    }
  }

  // One write for the lot: appendRow per word would be hundreds of calls.
  if (rows.length) {
    sheet.getRange(sheet.getLastRow() + 1, 1, rows.length, width).setValues(rows);
  }

  Logger.log('Added %s word(s): %s in "%s", %s in "%s".',
    rows.length, counts[chem.name] || 0, chem.name, counts[math.name] || 0, math.name);
  if (skipped) Logger.log('Skipped %s word(s) already in those folders.', skipped);
  Logger.log('Done. The app picks these up on its next sync.');
}
