/**
 * AddMunWords.gs — a one-off import. Run it once, then delete this file.
 *
 * Adds the 132 entries of 「MUN用 児童労働 英単語・英表現集（第81会期 GA第三委員会）」
 * as words in one folder, "MUN Child Labour". The English is the word and
 * the Japanese the definition; the third column of each table goes in the
 * note — usage notes, example sentences, or the full name of an acronym.
 *
 *   §1–3  terms          English · Japanese · 用法・注記
 *   §4    statistics     English · Japanese · 例文
 *   §5    clauses        English · Japanese · 用途 / 強度 (5-3 has no third column)
 *   §6    procedure      English · Japanese
 *   §7    speeches       the sentence · the situation (場面)
 *   §8    confusables    the words · the explanation (解説)
 *   §9    acronyms       acronym · Japanese · full name in the note
 *
 * How to run it
 *   1. Paste this file into the same Apps Script project as Code.gs — it uses
 *      the helpers there, so Code.gs must already be the current version.
 *   2. Pick addMunWords in the function list and press Run.
 *   3. Read the log for the count.
 *
 * Safe to run twice: an entry already in the folder is skipped, and nothing
 * already in the sheet is modified. All rows go in with a single write.
 */

var MUN_FOLDER = 'MUN Child Labour';

/** [English, part of speech, Japanese, note] */
var MUN_WORDS = [
  ["child labour", "Noun",
   "児童労働",
   "撤廃対象。可算・不可算に注意し、a child labour とは言わない"],
  ["child work / children's work", "Noun",
   "子供の仕事",
   "許容される労働。両者の区別を明示すると議論の精度が上がる"],
  ["the worst forms of child labour", "Noun",
   "最悪の形態の児童労働",
   "定冠詞 the を伴う定型句。ILO第182号条約の術語"],
  ["hazardous work", "Noun",
   "危険有害労働",
   "dangerous work ではなくこの語が公式用語"],
  ["minimum age for admission to employment", "Noun",
   "就業最低年齢",
   "ILO第138号条約の正式表現。短縮形は minimum working age"],
  ["light work", "Noun",
   "軽易労働",
   "13〜15歳に条件付きで認められる例外"],
  ["compulsory education", "Noun",
   "義務教育",
   "free and compulsory primary education の形で頻出"],
  ["economic exploitation", "Noun",
   "経済的搾取",
   "子どもの権利条約第32条の文言"],
  ["debt bondage / bonded labour", "Noun",
   "負債による奴隷労働",
   "第182号条約 第3条(a)"],
  ["forced labour", "Noun",
   "強制労働",
   "児童労働と並置されることが多い"],
  ["domestic work / domestic worker", "Noun",
   "家事労働／家事使用人",
   "「隠れた児童労働」の典型。housework は家庭内の無償家事を指し別語"],
  ["out-of-school children", "Noun",
   "不就学児童",
   "統計上の標準表現"],
  ["intergenerational transmission of poverty", "Noun",
   "貧困の世代間連鎖",
   "cycle of poverty, poverty trap も可"],
  ["human capital formation", "Noun",
   "人的資本形成",
   "経済的損失を論じる際の鍵語"],
  ["decent work", "Noun",
   "ディーセント・ワーク",
   "訳さず用いるのが慣例。SDGs目標8の中核概念"],
  ["the informal economy / informal sector", "Noun",
   "非公式経済",
   "black market とは意味が異なるので混同しないこと"],
  ["birth registration", "Noun",
   "出生登録",
   "公的支援からの漏れを論じる際に必須"],
  ["social protection floor", "Noun",
   "社会保護の床",
   "ILO第202号勧告の概念"],
  ["(conditional) cash transfer", "Noun",
   "（条件付き）現金給付",
   "就学条件付き給付は conditional cash transfer"],
  ["State party / signatory", "Noun",
   "締約国／署名国",
   "複数形は States parties（parties ではなく両方複数）"],
  ["ratification / accession / reservation", "Noun",
   "批准／加入／留保",
   "ratify a convention と動詞で使う"],
  ["labour inspectorate / labour inspection", "Noun",
   "労働監督機関／労働監督",
   "規制アプローチの実効性を論じる際の要語"],
  ["push factors / pull factors", "Noun",
   "送り出し要因／受け入れ要因",
   "供給側・需要側の整理に有用"],
  ["household income shock", "Noun",
   "世帯所得の急激な減少",
   "児童労働の引き金として頻出"],
  ["opportunity cost of schooling", "Noun",
   "就学の機会費用",
   "「働かせない損失」を経済学的に説明する語"],
  ["subsistence agriculture", "Noun",
   "自給的農業",
   "農業61%という統計の背景説明に"],
  ["social norms", "Noun",
   "社会規範",
   "deeply entrenched social norms の形で使う"],
  ["nimble fingers argument", "Noun",
   "器用な指先論",
   "需要側要因の学術的呼称"],
  ["low-skilled / unskilled labour", "Noun",
   "低技能・未熟練労働",
   "賃金押し下げ効果の議論に"],
  ["a race to the bottom", "Idiom",
   "底辺への競争",
   "労働基準の切り下げ競争を指す定型比喩"],
  ["to undercut competitors", "Expression",
   "不当に安く売って競合を出し抜く",
   "「悪貨が良貨を駆逐する」構造の説明に"],
  ["vicious circle / self-perpetuating", "Noun",
   "悪循環／自己再生産的",
   "a self-perpetuating cycle of poverty"],
  ["global supply chain / value chain", "Noun",
   "グローバル・サプライチェーン／バリューチェーン",
   "後者は付加価値の配分を含意"],
  ["upstream / downstream", "Adj",
   "上流／下流",
   "児童労働の90%以上は upstream に集中"],
  ["tier-1 / lower-tier suppliers", "Noun",
   "一次サプライヤー／下層サプライヤー",
   "監査が届かない層を指す"],
  ["unauthorised subcontracting", "Noun",
   "無許可の外部発注",
   "追跡困難の主因"],
  ["traceability", "Noun",
   "トレーサビリティ",
   "ensure full traceability"],
  ["human rights due diligence (HRDD)", "Noun",
   "人権デューデリジェンス",
   "略語は初出時に必ずフルスペルを示す"],
  ["mandatory vs. voluntary frameworks", "Noun",
   "義務的／自主的枠組み",
   "南北対立の主要な分岐点"],
  ["UN Guiding Principles on Business and Human Rights (UNGPs)", "Noun",
   "ビジネスと人権に関する指導原則",
   "protect, respect and remedy の三本柱"],
  ["grievance mechanism", "Noun",
   "苦情処理メカニズム",
   "救済（remedy）の実効性を論じる際に"],
  ["remediation", "Noun",
   "是正・救済措置",
   "解雇ではなく子どもの復学等を含む"],
  ["cut and run / responsible disengagement", "Expression",
   "取引の一方的打ち切り／責任ある関係解消",
   "一斉解雇問題を指摘する際の鍵語"],
  ["purchasing practices", "Noun",
   "調達慣行",
   "短納期・買い叩きが末端にしわ寄せする構造"],
  ["living wage", "Noun",
   "生活賃金",
   "最低賃金（minimum wage）とは別概念"],
  ["third-party certification / social audit", "Noun",
   "第三者認証／社会監査",
   "限界の指摘とセットで論じられる"],
  ["blockchain-based traceability", "Noun",
   "ブロックチェーンによる追跡",
   "ただし技術偏重はアウトオブアジェンダに接近する点に注意"],
  ["digital divide / capacity gap", "Noun",
   "デジタル格差／能力格差",
   "途上国・中小企業側の懸念を代弁する語"],
  ["data falsification", "Noun",
   "データ改ざん",
   "透明化の限界を突く際に"],
  ["ESG screening / divestment", "Noun",
   "ESG スクリーニング／投資撤退",
   "企業への圧力手段"],
  ["extraterritorial application", "Noun",
   "域外適用",
   "主権侵害の懸念と結びつく"],
  ["account for", "Verb",
   "〜を占める",
   "Agriculture accounts for 61 per cent of all child labour."],
  ["prevalence rate", "Noun",
   "（有病率的な意味での）発生率",
   "The prevalence rate stands at 22 per cent in sub-Saharan Africa."],
  ["disaggregated data", "Noun",
   "分類別データ",
   "data disaggregated by age, sex and sector"],
  ["a decline of X percentage points", "Expression",
   "X ポイントの低下",
   "%の変化幅は point、割合は per cent と使い分ける"],
  ["at the current pace", "Expression",
   "現在のペースでは",
   "At the current pace, Target 8.7 will not be met."],
  ["off track / on track", "Expression",
   "達成困難／順調",
   "The world remains significantly off track."],
  ["underreported", "Adj",
   "過少報告されている",
   "Domestic work remains systematically underreported."],
  ["per cent", "Noun",
   "パーセント",
   "国連文書では二語に分けるのが標準（× percent）"],
  ["Recalling", "Expression",
   "〜を想起し",
   "既存の条約・決議への言及。Recalling its resolution 80/190"],
  ["Reaffirming", "Expression",
   "〜を再確認し",
   "子どもの権利条約等の原則"],
  ["Noting with grave concern", "Expression",
   "重大な懸念をもって留意し",
   "1億3,760万人という数値の提示"],
  ["Deeply concerned", "Expression",
   "深く憂慮し",
   "危険有害労働5,400万人など"],
  ["Alarmed by", "Expression",
   "〜に驚愕し",
   "最も強い懸念表明"],
  ["Recognizing", "Expression",
   "〜を認識し",
   "各国の異なる事情への配慮を示す際に有効"],
  ["Bearing in mind", "Expression",
   "〜を念頭に置き",
   "開発段階の差異など"],
  ["Emphasizing / Stressing", "Expression",
   "〜を強調し",
   "根本原因への対処の必要性"],
  ["Acknowledging", "Expression",
   "〜を認め",
   "他国の立場に一定の理解を示す際"],
  ["Taking into account", "Expression",
   "〜を考慮し",
   "national circumstances と結びつけやすい"],
  ["Convinced that", "Expression",
   "〜と確信し",
   "自国の理念を打ち出す際"],
  ["Welcoming", "Expression",
   "〜を歓迎し",
   "ILO第182号条約の全加盟国批准達成など"],
  ["Invites / Suggests", "Expression",
   "〜するよう招請する／提案する",
   "最も弱い。合意形成が難しい論点に"],
  ["Encourages", "Expression",
   "〜するよう奨励する",
   "弱め。企業や民間主体に向けやすい"],
  ["Recommends", "Expression",
   "〜するよう勧告する",
   "やや弱め"],
  ["Requests", "Expression",
   "〜するよう要請する",
   "事務総長・国連機関に向けるのが通例"],
  ["Calls upon", "Expression",
   "〜するよう求める",
   "加盟国に向ける標準的表現"],
  ["Urges", "Expression",
   "〜するよう強く促す",
   "強め。反対票を招きやすい"],
  ["Strongly urges / Demands", "Expression",
   "強く要請する／要求する",
   "Demands は安保理向けで、総会では稀。使用は慎重に"],
  ["Decides to", "Expression",
   "〜することを決定する",
   "総会自身の行動（作業部会設置等）にのみ用いる"],
  ["Decides to remain seized of the matter", "Expression",
   "本件を引き続き検討する",
   "決議末尾の定型句"],
  ["in accordance with national law and circumstances", "Expression",
   "各国の国内法および事情に従って",
   ""],
  ["in a manner consistent with international obligations", "Expression",
   "国際的義務と整合する形で",
   ""],
  ["while respecting the sovereignty of States", "Expression",
   "国家主権を尊重しつつ",
   ""],
  ["taking into account the differing levels of development", "Expression",
   "発展段階の差異を考慮して",
   ""],
  ["on a voluntary basis", "Expression",
   "自主的な基礎の上に",
   ""],
  ["subject to the availability of resources", "Expression",
   "資源の利用可能性を条件として",
   ""],
  ["within existing mandates and resources", "Expression",
   "既存のマンデートおよび資源の範囲内で",
   ""],
  ["with the full and effective participation of", "Expression",
   "〜の完全かつ実効的な参加を得て",
   ""],
  ["as appropriate / where applicable", "Expression",
   "適切な場合には／該当する場合には",
   "交渉上の要点：下線部のような限定句（qualifiers）は、義務的な文言に抵抗する国が挿入を求める典型的な「軟化装置」である。逆に強い文言を望む国は、これらの削除を交渉材料とする。"],
  ["Point of Order", "Noun",
   "議事進行に関する発議（手続きの誤りの指摘）",
   ""],
  ["Point of Parliamentary Inquiry", "Noun",
   "手続きに関する質問",
   ""],
  ["Point of Personal Privilege", "Noun",
   "身体的支障に関する発議",
   ""],
  ["Motion to set the agenda", "Noun",
   "議題設定の動議",
   ""],
  ["moderated caucus / unmoderated caucus", "Noun",
   "モデレーテッド・コーカス／アンモデレーテッド・コーカス",
   ""],
  ["to yield the floor to", "Expression",
   "発言権を〜に譲る",
   ""],
  ["Right of Reply", "Noun",
   "答弁権",
   ""],
  ["working paper / draft resolution (DR)", "Noun",
   "ワーキングペーパー／決議案",
   ""],
  ["sponsors and signatories", "Noun",
   "提出国および賛同国",
   ""],
  ["friendly / unfriendly amendment", "Noun",
   "友好的修正／非友好的修正",
   ""],
  ["to move to divide the question", "Expression",
   "分割投票を動議する",
   ""],
  ["roll-call vote", "Noun",
   "記名投票",
   ""],
  ["to abstain / abstention", "Expression",
   "棄権する／棄権",
   ""],
  ["adopted by consensus / without a vote", "Expression",
   "コンセンサスで採択／投票によらず採択",
   ""],
  ["bracketed text", "Noun",
   "括弧付き文言（合意未成立部分）",
   ""],
  ["My delegation is of the view that … / The delegation of X firmly believes that …", "Expression",
   "立場表明",
   ""],
  ["We align ourselves with the remarks made by the distinguished delegate of X.", "Expression",
   "賛意",
   ""],
  ["While we appreciate the intention behind this proposal, we have reservations regarding …", "Expression",
   "穏当な反論",
   ""],
  ["We cannot accept language that imposes binding obligations on developing States.", "Expression",
   "明確な反対",
   ""],
  ["We would be prepared to support this clause, provided that the phrase “in accordance with national circumstances” is retained.", "Expression",
   "条件付き譲歩",
   ""],
  ["As a compromise, we propose replacing “urges” with “calls upon”.", "Expression",
   "妥協案の提示",
   ""],
  ["We should like to seek clarification on the intended scope of operative clause 4.", "Expression",
   "質問",
   ""],
  ["With respect, this matter falls outside the mandate of the Third Committee.", "Expression",
   "マンデート論",
   ""],
  ["We believe there is common ground between our positions on the question of education.", "Expression",
   "合意点の探索",
   ""],
  ["This constitutes a red line for my delegation.", "Expression",
   "譲れない一線",
   ""],
  ["Thank you, Mr./Madam Chair. My delegation yields the floor.", "Expression",
   "結語",
   ""],
  ["eliminate / eradicate / abolish / prohibit", "Verb",
   "eliminate は「なくす」（SDGs・ILO の標準語）、eradicate は「根絶する」でより強い、abolish は制度の「廃止」、prohibit は法による「禁止」。条約の禁止規定には prohibit、政策目標には eliminate が適合する",
   ""],
  ["developing countries / the Global South / LDCs", "Noun",
   "LDCs（後発開発途上国）は国連が定義する公式カテゴリー。the Global South は政治的含意を伴うため、公式文言では developing countries が無難",
   ""],
  ["victim / survivor / child in child labour", "Noun",
   "近年の国連文書は当事者性を尊重し a child engaged in child labour 等の表現を好む傾向にある",
   ""],
  ["shall / should / may", "Verb",
   "総会決議に法的拘束力はないため、shall の使用は原則として避け、加盟国への呼びかけは calls upon States to … の不定詞構文で表す",
   ""],
  ["Chairman / Chair", "Noun",
   "ジェンダー中立性の観点から Chair または Chairperson を用いる。呼びかけは Mr. Chair / Madam Chair",
   ""],
  ["manpower / workforce", "Noun",
   "manpower は避け、workforce, human resources を用いる",
   ""],
  ["ILO", "Acronym",
   "国際労働機関",
   "International Labour Organization"],
  ["ILC", "Acronym",
   "国際労働総会",
   "International Labour Conference"],
  ["IPEC", "Acronym",
   "国際児童労働撤廃計画",
   "International Programme on the Elimination of Child Labour"],
  ["UNICEF", "Acronym",
   "国連児童基金",
   "United Nations Children's Fund"],
  ["CRC", "Acronym",
   "児童の権利に関する条約",
   "Convention on the Rights of the Child"],
  ["UNGPs", "Acronym",
   "ビジネスと人権に関する指導原則",
   "UN Guiding Principles on Business and Human Rights"],
  ["HRDD", "Acronym",
   "人権デューデリジェンス",
   "Human Rights Due Diligence"],
  ["GSC", "Acronym",
   "グローバル・サプライチェーン",
   "Global Supply Chain"],
  ["CSR", "Acronym",
   "企業の社会的責任",
   "Corporate Social Responsibility"],
  ["EFA", "Acronym",
   "万人のための教育",
   "Education for All"],
  ["MSMEs", "Acronym",
   "零細・中小企業",
   "Micro, Small and Medium-sized Enterprises"],
];

/* --- The import ----------------------------------------------------------- */
/* Names here are distinct from the other import files, so any of them can sit
   in the same project without quietly replacing each other's helpers. */

function ensureMunFolder_() {
  var folders = listFolders_();
  for (var i = 0; i < folders.length; i++) {
    if (folders[i].name.toLowerCase() === MUN_FOLDER.toLowerCase()) return folders[i];
  }
  var created = createFolder_(MUN_FOLDER);
  Logger.log('Created folder "%s".', MUN_FOLDER);
  return created;
}

function addMunWords() {
  var sheet = getSheet_();
  var schema = ensureHeaders_(sheet);
  var width = schema.width;
  var folder = ensureMunFolder_().name;

  // What is already in the folder, so a second run adds nothing twice.
  var seen = {};
  var existing = listWords_();
  for (var e = 0; e < existing.length; e++) {
    if ((existing[e].folder || '').toLowerCase() === folder.toLowerCase()) {
      seen[existing[e].word.toLowerCase()] = true;
    }
  }

  var now = new Date().toISOString();
  var rows = [];
  var skipped = 0;

  for (var i = 0; i < MUN_WORDS.length; i++) {
    var entry = MUN_WORDS[i];
    if (seen[entry[0].toLowerCase()]) {
      skipped += 1;
      continue;
    }
    seen[entry[0].toLowerCase()] = true;

    // Through the same validation every saved word goes through.
    var fields = validate_({
      word: entry[0], pos: entry[1], definition: entry[2], note: entry[3],
      color: 'default', folder: folder, status: ''
    });
    rows.push(wordToRow_(buildRecord_(fields, Utilities.getUuid(), now, now), schema.map, width));
  }

  if (rows.length) {
    sheet.getRange(sheet.getLastRow() + 1, 1, rows.length, width).setValues(rows);
  }

  Logger.log('Added %s entr%s to "%s".', rows.length, rows.length === 1 ? 'y' : 'ies', folder);
  if (skipped) Logger.log('Skipped %s already in that folder.', skipped);
  Logger.log('Done. The app picks these up on its next sync.');
}
